cache:
 - "%LOCALAPPDATA%\\Yarn"

environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile
  - yarn run get all -p win32 --arch x64 -i ./bundle/internals -m ./bundle/modules

build_script:
  - yarn run build:win --c.directories.output=./bundle
  - ISCC ./windows/setup/main.iss
